"""Audited corrections for the H46-H160 Suno lyric source.

Each rule is a literal replacement applied after extraction-only normalization
(decimal/abbreviation joining and quote-mark removal).  Rules are scoped to a
lesson and must match exactly once; generation fails if the source drifts.
"""

from __future__ import annotations


CORRECTIONS: dict[int, list[tuple[str, str]]] = {
    46: [
        ("choose their representative through an election", "choose their representatives through elections"),
        ("Candidate run campaigns and present their policy", "Candidates run campaigns and present their policies"),
    ],
    47: [
        ("sells its product to gain profit", "sells its products to earn a profit"),
        ("where competition is active", "where competition is strong"),
        ("receive wage or salary", "receive wages or salaries"),
        ("gathers funds by tax", "raises funds through taxes"),
        ("uses them for the budget of education and welfare", "uses them to fund education and welfare"),
        ("provides loan", "provides loans"),
        ("Export and import support growth", "Exports and imports support growth"),
    ],
    48: [
        ("spends a great amount on advertising", "spends a great deal on advertising"),
        ("countless advertisement reach us", "countless advertisements reach us"),
        ("persuade them toward a purchase", "persuade consumers to make a purchase"),
        ("broadcast their opinion", "broadcast their opinions"),
        ("set up several regulation", "established regulations"),
    ],
    49: [
        ("fossil fuel", "fossil fuels"),
        ("The cutting of forests and the way of agriculture", "Deforestation and agricultural practices"),
        ("floods and droughts have become a frequent disaster", "floods and droughts have become more frequent"),
        ("Ecosystem are", "Ecosystems are"),
        ("Kyoto protocol", "Kyoto Protocol"),
        ("greenhouse gas", "greenhouse gases"),
        ("Paris agreement", "Paris Agreement"),
        ("the emission of cars and factories", "emissions from cars and factories"),
        ("future of the earth", "future of the Earth"),
    ],
    50: [
        ("according to the country one is born in and the income of one's family", "depending on the country where one is born and one's family income"),
        ("gaps in the quality and access of education", "gaps in access to and the quality of education"),
        ("forms his identity", "forms their identity"),
        ("the reduction of tuition", "reduced tuition"),
        ("open the chance of higher education", "open the opportunity for higher education"),
    ],
    51: [
        ("In some industry", "In some industries"),
        ("serious risk as well", "serious risks as well"),
        ("these consequence", "these consequences"),
        ("begun to build regulation for AI", "begun to develop regulations for AI"),
    ],
    52: [
        ("Countries imposed lockdown", "Countries imposed lockdowns"),
        ("Infected patient were carried to hospital", "Infected patients were taken to hospitals"),
        ("left us many lesson", "left us many lessons"),
        ("infectious disease cannot be stopped", "infectious diseases cannot be stopped"),
    ],
    53: [
        ("Urbanization has gathered opportunity", "Urbanization has concentrated opportunities"),
        ("move from the center of cities to the suburb", "move from city centers to the suburbs"),
        ("the line between city and rural life has become softer", "the distinction between urban and rural life has become less rigid"),
    ],
    54: [
        ("Athlete from across the world", "Athletes from across the world"),
        ("gather enthusiastic fan", "gather enthusiastic fans"),
    ],
    55: [
        ("one of the most aging societies", "one of the most rapidly aging societies"),
        ("The medical cost of the elderly increases", "Medical costs for older people increase"),
        ("Volunteer visit them", "Volunteers visit them"),
        ("between generation", "between generations"),
        ("a long-living society", "a long-lived society"),
    ],
    56: [
        ("the fourth power", "the fourth estate"),
        ("Journalist carry", "Journalists carry"),
        ("drove the American president to resign through their investigation", "helped expose abuses of power that led to the American president's resignation"),
        ("the power of the press can shake even authority itself", "the press can hold even the highest authorities accountable"),
    ],
    57: [
        ("lies on the line that Tesla's vision drew", "owes much to the vision that Tesla pursued"),
        ("pictured the foundation of", "envisioned the foundations of"),
        ("Many of his patent", "Many of his patents"),
    ],
    58: [
        ("Witness are", "Witnesses are"),
        ("fair to both victim and offender", "fair to both victims and offenders"),
        ("spent a long history refining", "spent centuries refining"),
    ],
    59: [
        ("our unconscious desire was", "our unconscious desires were"),
        ("the experiment of Stanley Milgram showed", "Stanley Milgram's experiments showed"),
        ("our decision is bent by many bias", "our decisions are distorted by many biases"),
        ("those who carry anxiety or depression", "people experiencing anxiety or depression"),
    ],
    60: [
        ("the age of nuclear weapon", "the age of nuclear weapons"),
        ("the number of refugee", "the number of refugees"),
        ("Many victim", "Many victims"),
    ],
    61: [
        ("the trait of pea plants", "the traits of pea plants"),
        ("the color of the seed, the shape of the seed", "seed color, and seed shape"),
        ("the scientist of the time", "the scientists of the time"),
        ("three independent researcher", "three independent researchers"),
        ("Mendel's law", "Mendel's laws"),
        ("His experiment finally", "His experiments finally"),
    ],
    62: [
        ("the world's ocean", "the world's oceans"),
        ("Larger plastic, broken down", "Larger pieces of plastic, broken down"),
        ("Whales and seabirds confused plastic bags with their food", "Whales and seabirds have mistaken plastic bags for food"),
        ("the ban of certain plastics", "banning certain plastics"),
        ("the choice each of us makes", "the choices each of us makes"),
    ],
    63: [
        ("wild chimpanzee", "wild chimpanzees"),
        ("enter the depth of Africa", "enter the interior of Africa"),
        ("made twigs into a tool", "made twigs into tools"),
        ("Her observation rewrote", "Her observations redrew"),
        ("the many youth", "the many young people"),
    ],
    64: [
        ("influential painter", "influential painters"),
        ("dark-toned painting", "dark-toned paintings"),
        ("geometric shape", "geometric shapes"),
    ],
    65: [
        ("The algorithm of social media is designed", "Social media algorithms are designed"),
        ("Anyone may have noticed", "Many of us have noticed"),
        ("the new illness of modern people", "serious problems in modern life"),
    ],
    66: [
        ("a kingdom and then a city-state republic, only a small town", "a kingdom and then a republic centered on a small city"),
        ("taken hold of the power of the Mediterranean", "taken control of the Mediterranean"),
        ("The senate and the consul", "The senate and the consuls"),
        ("internal disorder and the invasion of outsiders", "internal disorder and invasions by outside forces"),
        ("The story of an empire that had lasted for over a thousand years was thus closed", "The Western Roman Empire, after centuries of expansion and decline, thus came to an end"),
        ("Rome vanished, but its legacy", "The Western Empire fell, but Rome's legacy"),
    ],
    67: [
        ("86 billion neuron", "86 billion neurons"),
        ("through a synapse", "through synapses"),
        ("How consciousness rises", "How consciousness arises"),
        ("observe a brain in action", "observe the brain in action"),
        ("Alzheimer, Parkinson, stroke", "Alzheimer's disease, Parkinson's disease, and stroke"),
        ("suffer brain disease and brain injury", "suffer from brain diseases or brain injuries"),
    ],
    68: [
        ("Heavy tax weighed upon the peasant and the city poor", "Heavy taxes weighed on peasants and the urban poor"),
        ("the gap between them and the king Louis XVI and the queen Marie Antoinette", "the gap between ordinary people and the royal court of Louis XVI and Marie Antoinette"),
        ("These ideal", "These ideals"),
        ("French revolution", "French Revolution"),
        ("National assembly", "National Assembly"),
        ("The three ideal", "The three ideals"),
    ],
    69: [
        ("the first star ignited", "the first stars ignited"),
        ("a weak microwave radiation", "weak microwave radiation"),
        ("the same number of galaxy", "roughly the same number of galaxies"),
        ("the earth", "the Earth"),
    ],
    70: [
        ("dawn of the industrial revolution", "dawn of the Industrial Revolution"),
        ("The industrial revolution greatly", "The Industrial Revolution greatly"),
        ("labor condition", "labor conditions"),
        ("low wage", "low wages"),
        ("organize union", "organize unions"),
        ("the living standard", "living standards"),
    ],
    71: [
        ("tell story", "tell stories"),
        ("live the life of a person", "live the lives of people"),
        ("conflict of the character", "conflicts of the characters"),
        ("These novel", "These novels"),
        ("the depth of our heart", "the depths of our hearts"),
    ],
    72: [
        ("forced into evacuation from the land", "forced to evacuate the land"),
        ("first responder such as", "first responders such as"),
        ("hold evacuation drill regularly", "hold evacuation drills regularly"),
        ("passing on the lesson learned", "passing on the lessons learned"),
    ],
    73: [
        ("trillion cell", "trillion cells"),
        ("the tissue across the body", "tissues throughout the body"),
        ("various disease", "various diseases"),
        ("Physician listen", "Physicians listen"),
    ],
    74: [
        ("Such tradition is", "Such traditions are"),
        ("there are rite of passage", "there are rites of passage"),
    ],
    75: [
        ("seven thousand language", "seven thousand languages"),
        ("Japanese expression such as", "Japanese expressions such as"),
        ("deeply melted into them", "deeply embedded in them"),
        ("In reverse", "Conversely"),
        ("translators give long hours", "translators devote long hours"),
    ],
    76: [
        ("the decision to abandon one's homeland is heavy", "the decision to leave one's homeland is difficult"),
        ("Families would accompany one another on a long voyage", "Families traveled together on long voyages"),
        ("the culture of their ancestor", "the cultures of their ancestors"),
    ],
    77: [
        ("article on the internet", "articles on the internet"),
        ("An ad exists not to convey fact", "An advertisement exists not simply to convey facts"),
        ("encourage purchase", "encourage purchases"),
        ("have the eye to analyze", "examine critically"),
        ("It is not about doubting information", "It is not about doubting all information"),
    ],
    78: [("On the earth", "On Earth")],
    79: [
        ("the sights of space exploration are set even further", "the goals of space exploration are set even farther away"),
        ("full of obstacle", "full of obstacles"),
        ("loss of gravity", "microgravity"),
        ("brings alternative solutions", "brings new solutions"),
    ],
    80: [("from ancient Greece, 2500 years ago", "since ancient Greece, 2,500 years ago")],
    81: [
        ("reached an unknown continent", "reached the Americas"),
        ("from the sea to the land, to the sky, and to the poles", "to the poles, the highest mountains, the deep sea, and the sky"),
        ("the most difficult obstacle", "the most difficult obstacles"),
    ],
    82: [
        ("was founded thirty years ago at its headquarters in a regional city", "was founded thirty years ago in a regional city"),
        ("The numbers in the account were harsh", "The figures in the accounts were discouraging"),
        ("convinced investor after investor and gathered fund", "convinced investor after investor and raised funds"),
        ("won contract with overseas client", "won contracts with overseas clients"),
        ("Transparency of administration", "Transparency in management"),
    ],
    83: [
        ("Film critic evaluate", "Film critics evaluate"),
        ("Award such as", "Awards such as"),
        ("What impress us", "What impresses us"),
        ("beauty of the image", "beauty of the images"),
    ],
    84: [
        ("chemical fertilizer", "chemical fertilizers"),
        ("pesticide and fertilizer", "pesticides and fertilizers"),
        ("genetically modified gene technology", "genetically modified crops"),
        ("To feed the earth", "To feed the world"),
    ],
    85: [
        ("unable to pay the fee", "unable to pay school fees"),
        ("These disadvantage", "These disadvantages"),
        ("Through scholarship", "Through scholarships"),
    ],
    86: [
        ("When civilian raise their voices", "When citizens raise their voices"),
        ("taking part in the enforcement of law", "taking part in upholding the law"),
    ],
    87: [
        ("I was not afraid to get up — I was simply bored", "I was not eager to get up — I was simply bored"),
        ("a clerk I knew by face", "a clerk I knew by sight"),
        ("I charged it to my card", "I paid by card"),
        ("I buried my precious ring in the garden", "I lost my precious ring in the garden"),
        ("I did not feel it a bother", "I did not mind helping"),
        ("What a charm you have", "What good luck you bring"),
        ("agree to come camping", "come camping"),
        ("I accepted at once", "I accepted the invitation at once"),
    ],
    88: [
        ("Only a shelf attached to the wall left a faint clue", "Only a shelf fixed to the wall seemed out of place"),
        ("An evident motive, physical evidence, and the device of a key left behind", "A clear motive, physical evidence, and a discarded key mechanism all pointed to him"),
        ("hiding in the nearest place", "hiding in plain sight"),
    ],
    89: [
        ("to elect is the most fundamental act", "voting is one of the most fundamental civic acts"),
        ("choose their representative", "choose their representatives"),
        ("approval from the assembly", "approval from the legislature"),
        ("those who do not vote are not entitled to complain about the result", "those who do not vote lose an important opportunity to shape the result"),
    ],
    90: [
        ("The data obtained is put through analysis and comparison with the hypothesis", "The data obtained are analyzed and compared with the hypothesis"),
        ("If the hypothesis is denied", "If the hypothesis is rejected"),
    ],
    91: [
        ("scent of fresh bread and flavor of rich spice drifted", "scent of fresh bread and the aroma of rich spices drifted"),
        ("stayed at a white village estate", "stayed at an inn in a whitewashed village"),
        ("The wind blew with ease", "The wind blew gently"),
        ("far more broad", "far broader"),
    ],
    92: [
        ("placed limitation", "placed limitations"),
        ("Activist continue", "Activists continue"),
        ("protect the victim", "protect victims"),
    ],
    93: [
        ("But as a cost", "But at a cost"),
        ("The function of the lung weakens", "Lung function weakens"),
        ("muscle diminishes", "muscle mass diminishes"),
        ("is increasingly growing", "is growing"),
        ("small daily habit", "small daily habits"),
    ],
    94: [
        ("Numerous resident", "Numerous residents"),
        ("cheaper suburb", "cheaper suburbs"),
    ],
    95: [
        ("learning the craft", "learning the skills of the job"),
        ("potentially great reward", "potentially great rewards"),
        ("changing their profession", "changing professions"),
    ],
    96: [
        ("Alliance, treaty", "Alliances, treaties"),
        ("resolve disputes peacefully through resolution", "resolve disputes peacefully through negotiation"),
        ("regional conflict", "regional conflicts"),
    ],
    97: [
        ("species of mammal", "species of mammals"),
        ("On the earth", "On Earth"),
        ("the earth's surface", "the Earth's surface"),
        ("torments whale and turtle", "harms whales and turtles"),
        ("A certain tribe", "One Indigenous community"),
        ("established a pioneer model", "established a pioneering model"),
    ],
    98: [
        ("Electric device", "Electronic devices"),
        ("electrification of vehicle", "electrification of vehicles"),
        ("eliminate exhaust gas", "reduce exhaust emissions"),
        ("the problem of privacy exposure and the digital divide are", "the problems of privacy loss and the digital divide are"),
        ("distribute the benefit", "distribute the benefits"),
    ],
    99: [
        ("We commit a fault, and we regret", "We make mistakes, and we feel regret"),
        ("To push down that impulse", "To overcome that fear"),
    ],
    100: [
        ("portrait from the fifteenth century", "portraits from the fifteenth century"),
        ("impression paintings", "Impressionist paintings"),
        ("Something this painting inspired stayed firmly within me", "Something the painting awakened remained with me"),
        ("historian background", "historical background"),
        ("forms of nutrition", "forms of nourishment"),
    ],
    101: [
        ("the detail of the case with method", "the details of the case methodically"),
        ("several witness", "several witnesses"),
        ("several clue", "several clues"),
        ("the jury concluded", "the jury reached a verdict"),
    ],
    102: [
        ("themselves of yesterday", "the people they were yesterday"),
        ("Frequent practice produces a tremendous result", "Consistent practice produces remarkable results"),
        ("thousands of athlete", "thousands of athletes"),
        ("undergoes an injury", "suffers an injury"),
        ("On the back of one running desperately, there is something", "In the figure of a runner giving everything, there is something"),
        ("did not take a medal", "did not win a medal"),
        ("Ethnic and religion", "Ethnicity and religion"),
    ],
    103: [
        ("a shelf of poet", "a shelf of poetry"),
        ("when I opened the pages", "when I opened it"),
    ],
    104: [
        ("The causes were combined", "The causes were multiple"),
        ("households hold asset", "households hold assets"),
    ],
    105: [
        ("his days had been flowing slowly", "his days have passed slowly"),
        ("His wife had passed away", "His wife passed away"),
        ("many regret", "many regrets"),
        ("I wished we had traveled", "I wish we had traveled"),
        ("The transition of life", "The passage of life"),
    ],
    106: [
        ("the love and choice of two individuals is", "the love and choices of two individuals are"),
        ("difference in values", "differences in values"),
        ("has substantial impact", "has a substantial impact"),
    ],
    107: [
        ("corridor of the emergency hospital", "corridor of the emergency department"),
        ("with practiced motion", "with practiced movements"),
        ("swept the sweat", "wiped the sweat"),
        ("At medical sites", "In medical settings"),
    ],
    108: [
        ("there is a fear", "there was a fear"),
        ("An armed troop advances", "An armed unit advanced"),
        ("Everyone holds", "Everyone held"),
        ("Bullet flew", "Bullets flew"),
        ("Combat had begun", "Combat began"),
        ("Some are driven to PTSD, depression, or suicide", "Some develop PTSD or depression, and some are driven to suicide"),
    ],
    109: [
        ("a fixed share of cost", "a fixed share of the costs"),
        ("a monthly premium, like a deposit, and taxes", "monthly premiums and taxes"),
        ("withdrawn from the salary of employees of large companies", "deducted from employees' salaries"),
        ("pools a fund", "pools funds"),
    ],
    110: [
        ("As a single human being, we are absolutely small", "As individual human beings, each of us is very small"),
        ("human work seems insignificant", "human activity seems insignificant"),
        ("hold the same question", "hold the same questions"),
        ("no definitely clear answer", "no definitive answer"),
        ("Neither psychologist nor philosopher", "Neither psychologists nor philosophers"),
    ],
    111: [
        ("without regard to day nor night", "regardless of day or night"),
        ("we were chased by feeding and changing diapers", "we were kept busy with feeding and changing diapers"),
        ("the beat of his breast", "the heartbeat in his chest"),
        ("considerably happy", "deeply happy"),
        ("will walk through a long progression", "will develop over a long journey"),
    ],
    112: [
        ("a possession that only humans possess", "a capacity that may be uniquely human"),
        ("I spoiled a relationship", "I damaged a relationship"),
        ("contact was cut", "we lost touch"),
        ("Through rumors from a neighbor", "Through news from a mutual friend"),
        ("a single thank you", "a simple thank you"),
    ],
    113: [
        ("full of contradiction", "full of contradictions"),
        ("An inhabitant who has become materially wealthy feels only an inferior form of happiness in spirit", "A person who is materially prosperous may still feel unhappy inside"),
        ("chances to compare others with ourselves", "chances to compare ourselves with others"),
        ("Psychologist indicate", "Psychologists indicate"),
        ("the consequence is serious", "the consequences are serious"),
        ("keep distance", "keep our distance"),
        ("the heart that appreciates oneself", "a sense of self-acceptance"),
    ],
    114: [
        ("A socially designed experiment", "A large social experiment"),
        ("whether the wallet came back", "whether the wallet was returned"),
        ("Tested on street corners", "Conducted in public places"),
        ("on the counter", "on the contrary"),
        ("suggests that humans are essentially good", "suggests that people care about others and about seeing themselves as honest"),
        ("rests on a positive reality", "can rest on evidence from ordinary life"),
    ],
    115: [
        ("A correspondent sending reports from a war zone is a vital means to inform us", "Correspondents reporting from war zones play a vital role in informing us"),
        ("prepared for every exposure to danger", "constantly exposed to danger"),
        ("are transported across the world", "are transmitted around the world"),
        ("refugees who have lost their home", "refugees who have lost their homes"),
        ("children without intervention", "children deprived of safety and education"),
        ("victims of murder, accident, and assault", "victims of murder, accidents, and attacks"),
        ("who continue to carry the truth at risk", "who continue to report the truth at great risk"),
    ],
    116: [
        ("showed his emotions outside", "showed his emotions openly"),
        ("came to interpret him", "came to understand him"),
        ("Remembering itself calls pain", "Remembering itself causes pain"),
        ("intimate thoughts toward family", "private feelings about his family"),
        ("uncomfortable for him", "difficult for him"),
        ("Words had not been useless", "His silence did not mean that words were useless"),
        ("I briefly join my hands", "I briefly join my hands in prayer"),
    ],
    117: [
        ("carries an unprecedented complexity", "faces unprecedented complexity"),
        ("its own interest", "its own interests"),
        ("The extent of globalization has become deeper", "Global interdependence has deepened"),
        ("A financial crisis in one country expands", "A financial crisis in one country spreads"),
        ("transfers across continents", "crosses continents"),
        ("a definite commitment", "a firm commitment"),
        ("Reasonable action", "Effective action"),
        ("initiative to end poverty", "initiatives to end poverty"),
        ("These are all vote", "These are all votes"),
    ],
    118: [
        ("has significantly continued to rise", "has continued to rise significantly"),
        ("various reaction", "various reactions"),
        ("Politician, as they serve as politicians, turn", "Politicians often turn"),
        ("many contribution", "many contributions"),
        ("move voluntary", "move voluntarily"),
        ("a society that coldly reject", "a society that coldly rejects"),
    ],
    119: [
        ("A grammar teacher", "An art teacher"),
        ("he was too late to begin", "he was too old to begin"),
        ("calms his nerve", "calms his nerves"),
        ("the best solution to old age", "a powerful answer to the challenges of old age"),
        ("My grandfather's figure demonstrates this", "My grandfather's example demonstrates this"),
    ],
    120: [
        ("serious implication", "serious implications"),
        ("Go die", "You should die"),
        ("Some reach suicide", "Some die by suicide"),
        ("Words have consequence", "Words have consequences"),
        ("both weapon and medicine", "both a weapon and a medicine"),
    ],
    121: [
        ("The ice sheet of the Arctic", "The sea ice of the Arctic"),
        ("The primarily cause", "The primary cause"),
        ("If the ice sheet melts, sea levels rise", "At the same time, melting land ice and warming oceans are raising sea levels"),
        ("Their inhabitants are being pushed toward abandonment", "Their residents may eventually be forced to leave their homelands"),
        ("brings multiple times the greenhouse effect", "has many times the warming effect of carbon dioxide"),
        ("commission after commission, and commissioner debate", "committee after committee, and representatives debate"),
    ],
    122: [
        ("Dogs derive from wolves", "Dogs descended from wolves"),
        ("play various role", "play various roles"),
        ("owners who line up excuse", "owners who make excuses"),
        ("meet an unfortunate fate", "may never find new homes"),
        ("should not have the thought to dispose of them", "must never treat them as disposable"),
        ("Without disturb to this bond, we should keep caring for it", "We should protect this bond by caring for animals responsibly"),
    ],
    123: [
        ("was pushed to mental breakdown", "experienced severe mental distress"),
        ("had earned only the price of a single painting", "had sold only one painting"),
        ("support from his brother", "support of his brother"),
        ("no one could perceive his potential", "few people recognized his potential"),
        ("The exception was only his brother Theo", "His brother Theo was one of the few exceptions"),
        ("Is success to leave recognition after death", "Is success to be recognized after death"),
        ("inside the canvases", "in the canvases"),
    ],
    124: [
        ("a different preference", "different preferences"),
        ("there is a stronger inclined", "there is a stronger inclination"),
        ("seek a value", "seek values"),
        ("a phase shift of values", "a shift in values"),
        ("Resistance to rating and status", "Resistance to labels and status"),
        ("the truly satisfactory fulfillment", "truly satisfying fulfillment"),
    ],
    125: [
        ("target gaps in the human heart", "target human vulnerabilities"),
        ("loses normal reaction", "loses normal judgment"),
        ("please give the money by delivery right now", "please send the money immediately"),
        ("password or verbal authentication", "password or verification code"),
        ("first become calm", "first calm down"),
        ("it is obviously a fraud", "it is almost certainly fraud"),
        ("Police hotlines and the establishment of consumer centers will respond kindly", "Police hotlines and consumer centers can provide help"),
        ("there is no need to suppress that feeling", "do not let that feeling prevent you from pausing to verify the facts"),
    ],
    126: [
        ("cherry blossoms began to open", "cherry blossoms begin to open"),
        ("everyone swallows their breath", "everyone holds their breath"),
        ("gives off a unique beauty", "has a unique beauty"),
    ],
    127: [
        ("Earthquake resistance in each facility and the formation of evacuation plans have become a proper procedure for the state and its regions", "Strengthening buildings and preparing evacuation plans have become standard responsibilities for national and local governments"),
        ("a portable radio whose maintenance is kept up", "a well-maintained portable radio"),
        ("an available place", "an accessible place"),
        ("First lower yourself and hide under a desk", "First drop, cover your head, and hold on under a sturdy desk"),
        ("If you are using fire, put it out", "After the shaking stops, turn off flames if it is safe to do so"),
        ("flee with naked feet", "evacuate barefoot"),
        ("in chaos you may be able to reach nowhere", "you may be unable to contact one another in the confusion"),
        ("Take actions that would normally not be needed", "Take actions that you hope will prove unnecessary"),
        ("a matter of consideration and a matter of habit", "a matter of planning and habit"),
        ("If you prepare, you will have no regret", "Better safe than sorry"),
    ],
    128: [
        ("wrong operation", "wrong maneuver"),
        ("AI operates many parts of driving", "AI handles many driving tasks"),
        ("the initial level 2", "Level 2"),
        ("a traffic jam", "traffic jams"),
        ("Accidents caused by human inattention, fatigue, or drunk driving do not happen with AI", "Accidents caused by human inattention, fatigue, or drunk driving could be reduced, although AI introduces risks of its own"),
        ("Technological advance", "Technological progress"),
    ],
    129: [
        ("important instrument", "important partners"),
        ("pesticides whose ingredient includes neonicotinoids", "pesticides containing neonicotinoids"),
        ("this pesticide", "these pesticides"),
        ("strengthening restrict", "strengthening restrictions"),
        ("Farmers' yields fall", "Farmers worry that yields may fall without effective alternatives"),
        ("profit against the environment", "agricultural productivity against environmental protection"),
        ("operate within the circuit", "function within the network"),
        ("affected in sequence", "affected throughout the food chain"),
    ],
    130: [
        ("like a shared pronunciation", "like a universal language"),
        ("has proved", "has shown"),
        ("patients of dementia", "patients with dementia"),
        ("their expression is restored", "their expressions may return"),
        ("Budget restriction", "Budget restrictions"),
        ("listen to music from the heart", "listen attentively to music"),
    ],
    131: [
        ("would dare to take the boat out even on stormy days", "would set out before dawn and judge the changing weather with care"),
        ("the nets would pile with silver fish", "the nets would fill with silver fish"),
        ("Dealer waited", "Dealers waited"),
        ("His feeling to preserve", "His desire to preserve"),
        ("the change of the age", "changes in the times"),
        ("Fishing too must update", "Fishing methods must evolve"),
        ("we reserved closed fishing zones", "we established closed fishing zones"),
        ("scientific proof, we investigate", "scientific evidence, we monitor"),
    ],
    132: [
        ("The cause was so small", "The incident that triggered it was so small"),
        ("a certain mate", "one teammate"),
        ("inside the interior of my desk", "inside my desk"),
        ("referred the matter", "reported the matter"),
        ("Several fellow from the class", "Several classmates"),
        ("The wound does not completely disappear", "The wound has not completely disappeared"),
        ("becomes a force that can", "can become a strength that may"),
    ],
    133: [
        ("treated as false and invalid", "declared unconstitutional and invalid"),
        ("The results of a poll have", "Poll results have"),
        ("The constitution is not dependent on any one group", "The constitution does not belong to any one group"),
    ],
    134: [
        ("My family raises", "My family is raising"),
        ("Their similarity is surprisingly strong", "Their resemblance is striking"),
        ("can be astonish", "can be astonished"),
        ("power of representation", "power of expression"),
        ("identical twins should be the same", "identical twins share nearly the same genes"),
        ("each one's strength", "each child's strengths"),
        ("I am fairly looking forward", "I am eagerly looking forward"),
    ],
    135: [
        ("steam appear", "steam appears"),
        ("The master of the inn", "The innkeeper"),
        ("fixes the temperature", "adjusts the temperature"),
        ("His intellectual manner of speech", "His measured manner of speech"),
        ("Their dialect varies", "Their dialects vary"),
        ("The healing of a hot spring", "The relaxation of a hot spring"),
        ("raw ingredients", "ingredients"),
        ("the master recite", "the innkeeper recites"),
        ("have been traditionally passed down", "have been passed down orally"),
    ],
    136: [
        ("an eternal issue", "an enduring issue"),
        ("Whether democrat or republican", "Whether Democrat or Republican"),
        ("If a company grants money", "If a company donates money"),
        ("To become a supporter of a corporation carries an implied expectation", "Corporate support may therefore carry an implied expectation"),
        ("many minister", "many ministers"),
        ("methods that imitate and evade", "methods that circumvent"),
        ("Political fund organizations, fundraising parties, loopholes are many", "Political funding organizations and fundraising events can create many loopholes"),
        ("The watch of citizens, the investigator reporting", "Public scrutiny, investigative reporting"),
        ("For one's vote to carry meaning as a voter, the responsibility to watch politics must be fulfilled", "For a vote to carry meaning, citizens must also accept the responsibility of watching politics closely"),
    ],
    137: [
        ("was a theme that developed nations somewhat wanted to forget", "was a problem that many developed nations preferred to ignore"),
        ("an agricultural scientist stood up", "an agricultural scientist took action"),
        ("grew even in areas with little rainfall", "performed well in areas with limited rainfall"),
        ("It was necessary to praise him aloud", "His achievement received worldwide recognition"),
        ("these criticism", "these criticisms"),
        ("ethical subject", "ethical issues"),
        ("the highest priority issue that every country's ministry should face with confidence", "a high-priority issue that every government must confront"),
        ("the lesson Borlaug left us", "the lessons Borlaug left us"),
    ],
    138: [
        ("one of humanity's arts", "one of humanity's major art forms"),
        ("the actor's facial expression and gesture", "the actors' facial expressions and gestures"),
        ("kept alive on thick soup and old bread", "survived on simple soup and stale bread"),
        ("Chaplin's honor was restored", "Chaplin's reputation was restored"),
        ("The twelve-minute applause was the longest in Oscar history", "The prolonged applause became one of the most memorable moments in Oscar history"),
    ],
    139: [
        ("a formal state program", "national space programs"),
        ("rather than a lord's fantasy", "rather than a work of science fiction"),
        ("But practically", "But in practice"),
        ("To cure these problems", "To solve these problems"),
        ("atmosphere's constitute is", "atmosphere consists"),
        ("increases its confidence of survival", "increases its chances of survival"),
        ("There is legitimate basis", "There is a legitimate basis"),
    ],
    140: [
        ("a housewife for long years", "a homemaker for many years"),
        ("my mother was willing", "my mother was determined"),
        ("listen to radio English conversation", "listen to English lessons on the radio"),
        ("rubbing the words into her memory", "committing the words to memory"),
        ("Even quite short time", "Even a short amount of time"),
        ("Soon she plans", "She is now planning"),
        ("To walk the world on her own feet in English", "To make her own way through the world in English"),
    ],
    141: [
        ("fermented food", "fermented foods"),
        ("local community is strong", "local communities are strong"),
        ("healthy lifespan", "healthy life expectancy"),
        ("Fast food, traveling by car after parking, a mixture of food cultures", "Fast food, greater reliance on cars, and increasingly international diets"),
        ("key to holding a healthy, long life", "key to maintaining a long and healthy life"),
    ],
    142: [
        ("legal procedures on the shop floor", "safety procedures on the shop floor"),
        ("Regardless of Mariko's appointment", "Despite Mariko's appointment"),
        ("Under her managerial skill", "Under her management"),
        ("not to yield when interrupted", "not to yield when confronted with obstacles"),
    ],
    143: [
        ("I kept spinning the scales", "I kept repeating scales"),
        ("knew the joy", "came to know the joy"),
        ("I continued piano", "I continued playing the piano"),
        ("strength in her tip", "strength in her fingertips"),
        ("feeling for the pedal with her toe overlaps with my own figure", "stretching her toes toward the pedal recalls my own image"),
        ("it include all", "it contains all"),
    ],
    144: [
        ("a crippled life began", "his life with a disability began"),
        ("were despairing", "were filled with despair"),
        ("just walking took hours", "learning to walk again took months"),
        ("resented himself alone", "grieved alone"),
        ("yield to depress", "yield to depression"),
        ("license of a certified accountant", "qualification of a certified public accountant"),
        ("went independent as a consultant in the economics of small and medium businesses", "became an independent financial consultant for small and medium-sized businesses"),
        ("With exact calculation", "With precise calculations"),
        ("Riding a bicycle was unlikely", "He could not ride a bicycle"),
        ("works voluntary", "works as a volunteer"),
        ("to lose is also the beginning of rebirth", "loss does not have to be the end of a meaningful life"),
        ("Hardship deepens a person", "Hardship can deepen a person's understanding"),
    ],
    145: [
        ("handle the books properly", "handle the books carefully"),
        ("a silence like a unique chamber", "a quiet atmosphere like a private reading room"),
        ("treasure-like books", "treasured books"),
    ],
    146: [
        ("in the countryside of the county", "in the countryside"),
        ("a wide lawn and fields", "a large garden and fields"),
        ("When I would leap in", "When I leapt in"),
        ("felt squeezed", "felt breathless"),
        ("would quietly submit the tales", "would quietly tell me the stories"),
        ("cannot substitute", "cannot replace"),
    ],
    147: [
        ("passed on parallel to", "passed on from one generation to"),
        ("By one individual's strength alone", "Through one individual's strength alone"),
        ("rid oneself from poverty", "escape poverty"),
        ("It advertised the fact", "It demonstrated"),
        ("To accuse someone of poverty is a matter of human rights, not of economics, he said", "Yunus argued that poverty reflects social systems rather than personal failure"),
        ("has been created", "has emerged"),
        ("manage a minimum life", "make ends meet"),
        ("born in education from the income of parents", "in education caused by parents' income"),
        ("those who absorb it", "those who experience it"),
    ],
    148: [
        ("dealing with the need to rid the streets of suspicious persons", "responding to reports of suspicious activity while respecting civil rights"),
        ("communication with an editor", "communication with a supervisor"),
        ("The role of the facility that manages a prisoner", "The role of correctional facilities that manage prisoners"),
        ("moments that frighten", "dangerous moments"),
        ("gunshots, explosion", "gunshots, explosions"),
        ("bear a risk to", "face risks to"),
        ("not a rebel against", "not a rebellion against"),
        ("Mutual understanding and cooperation is", "Mutual understanding and cooperation are"),
    ],
    149: [
        ("the latest Amazon warehouse", "a large Amazon warehouse"),
        ("my knee hurt", "my knees hurt"),
        ("messages from my lover", "messages from my partner"),
        ("an analyst of my subordinates' journal records", "responsible for analyzing my team's work logs"),
        ("is precious", "is valuable"),
    ],
    150: [
        ("the globe is predicted", "the world is predicted"),
        ("cutting extra meat", "reducing excessive meat consumption"),
        ("Gene-editing technology is also hoped for", "Gene-editing technology also offers hope"),
        ("an issue in which favor and concern involve each other", "an issue that brings both promise and concern"),
        ("may be a convert that removes environmental burden", "may be an alternative that reduces environmental burdens"),
        ("Clean up the mess and reduce food loss", "Plan meals, use leftovers, and reduce food waste"),
    ],
    151: [
        ("a terrorist's seize", "a seizure by terrorists"),
        ("states were exclude", "states were excluded"),
        ("from its principal position", "because of its security policy"),
        ("This is not an ethically desirable stance", "This tension remains the subject of ethical and security debate"),
        ("should also be abolishable", "should also be capable of abolition"),
    ],
    152: [
        ("the root of Muslim and Christian religions", "a root of Christianity and Islam"),
        ("humanity's myth", "humanity's myths"),
        ("the Jews continued to bear and keep", "Jewish communities continued to preserve"),
        ("the Jewish contribution should be credit", "Jewish contributions should be credited"),
        ("both have victim", "both have victims"),
        ("a tool that unify", "a tool that unites"),
    ],
    153: [
        ("Artisans initially begin from long apprenticeship", "Artisans often begin with a long apprenticeship"),
        ("0.0001 millimeters thin", "0.0001 millimeters thick"),
        ("palm is the proof", "hands are proof"),
        ("interpretation of Japanese art", "expression of Japanese art"),
        ("choose industrialize mass production work", "choose industrialized, mass-production work"),
        ("the index that", "the belief that"),
        ("increases invest", "increases investment"),
        ("regarding Instagram", "on Instagram"),
        ("Recommendation from foreigners", "Interest from people overseas"),
    ],
    154: [
        ("vice branch manager", "deputy branch manager"),
        ("a folded letter", "a handwritten letter"),
        ("no dignity of a bishop", "never been an imposing manager"),
        ("an around-the-world trading trip", "an around-the-world trip"),
        ("A length of three months at sea", "Three months at sea"),
        ("the Mexican Gulf", "the Gulf of Mexico"),
        ("bought item", "bought items"),
        ("dinners in suit and dress, music of a high pitch", "dinners in formal dress, and polished evening music"),
        ("the slow relation", "the close relationship"),
        ("how we rear our grandchildren", "how we helped raise our grandchildren"),
        ("log our memories", "record our memories"),
        ("were varied", "were diverse"),
        ("Life is a continuation of etc", "Life is a continuing series of stages"),
    ],
    155: [
        ("cannot win the war even when they return to society", "may find that the battle does not end when they return to society"),
        ("lives can be lost in the life that follows", "lives can still be lost in the years that follow"),
        ("would become mad", "would panic or become angry"),
        ("Michael otherwise could not sleep", "Michael also could not sleep"),
        ("rely on drug", "rely on drugs"),
        ("But it cannot win you", "But it does not have to define you"),
        ("nation that started the war", "nation that sent them to war"),
    ],
    156: [
        ("many other province (local governments)", "many other local governments"),
        ("have passed thirty except some", "now include many countries and jurisdictions"),
        ("Opponents emphasis", "Opponents emphasize"),
        ("Is only that which continues from prior times correct", "Is something correct simply because it has continued from the past"),
        ("Workplace environments considerate of LGBTQ+ people alike", "Workplace environments that respect LGBTQ+ people"),
        ("Diversity is equivalent to a source", "Diversity is a source"),
    ],
    157: [
        ("In Japanese settlement", "In Japanese communities"),
        ("The stories spilled out of these are heard in the ears from childhood", "Stories about them have been passed down since childhood"),
        ("They were a roll of the wisdom", "They embodied the wisdom"),
        ("messenger of the god Inari", "messenger of the deity Inari"),
        ("a pit on its head", "a dish on its head"),
        ("the throat parts of mountains", "mountainous regions"),
        ("make ascetics bend", "test mountain ascetics"),
        ("The emphasis that humans cannot rule nature", "They emphasized that humans cannot rule nature"),
        ("As traditional regime is being lost", "As traditional customs are being lost"),
        ("imagination of maker", "imagination of creators"),
        ("whereas everything can be explained", "when everything seems explainable"),
    ],
    158: [
        ("Ordering on behalf of yourself", "Ordering for yourself"),
        ("do not expose to hide emotions", "do not try to hide their opinions or emotions"),
        ("as if to bet on it", "openly"),
        ("Hundreds of millions of people have no health insurance", "Millions of people have no health insurance"),
        ("bind their life to debt", "fall deeply into debt"),
        ("a woman almost asleep walking alone", "a person walking alone"),
        ("like a bishop, pay too much heed", "often pay too much attention"),
        ("your own country is plain to see", "you see your own country more clearly"),
        ("Experience abroad is one clip at a time", "Experience abroad is made up of individual encounters"),
        ("Piled together, they shape me, as a participant", "Together, they have shaped me as a person"),
    ],
    159: [
        ("Today's affair", "Today's event"),
        ("has effect", "has an effect"),
        ("for cancer patients in an abortion crisis of time", "for cancer patients facing an urgent need for new treatment"),
        ("The terms of the clinical trial", "The conditions of the clinical trial"),
        ("data was arranged", "data were arranged"),
        ("graduate pupil", "graduate students"),
        ("power of ally", "power of teamwork"),
    ],
    160: [
        ("high heel shoes", "high-heeled shoes"),
        ("Shit, we have no time", "We have no time"),
        ("we beg you to work without even water", "we have asked you to work without a proper break"),
        ("accommodation of diverse body types", "inclusion of diverse body types"),
        ("sacrifice the earth", "sacrifice the Earth"),
    ],
}


def apply_lesson_corrections(lesson: int, lines: list[str]) -> tuple[list[str], list[dict[str, str]]]:
    """Apply and audit literal replacements for one lesson."""
    corrected = list(lines)
    changes: list[dict[str, str]] = []
    for old, new in CORRECTIONS.get(lesson, []):
        matches = [(i, line.count(old)) for i, line in enumerate(corrected) if old in line]
        total = sum(count for _, count in matches)
        if total != 1:
            raise ValueError(f"H{lesson}: correction source must match exactly once: {old!r} (matched {total})")
        index = matches[0][0]
        before = corrected[index]
        corrected[index] = before.replace(old, new, 1)
        changes.append({"before": before, "after": corrected[index]})
    return corrected, changes
